-- MySQL Script generated by MySQL Workbench
-- Sun Nov 24 17:23:59 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyectoboites
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyectoboites
-- -----------------------------------------------------
CREATE SCHEMA `proyectoboites` DEFAULT CHARACTER SET utf8 ;
USE `proyectoboites` ;

-- -----------------------------------------------------
-- Table `proyectoboites`.`contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectoboites`.`contacto` (
  `idcontacto` INT NOT NULL,
  `avatar` LONGTEXT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `facebook` VARCHAR(60) NOT NULL,
  `instagram` VARCHAR(60) NOT NULL,
  `twitter` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idcontacto`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
